### ISSUE TITLE
Lista documentos .html

### ISSUE THREAD

**Issue by amiedes** [UCM-SistemasWeb-Veery/UCM-SistemasWeb-Veery.github.io#1]
## 1. OTROS 

index.html - Muestra también las noticias (Rafa)
login.html -  (Rafa)

registro.html (df_register_user.jpg) (Nacho)
busqueda.html (df_search_results.jpg) (Nacho)
## 2. VISUALIZACIÓN DE CONTENIDOS (Denys Ruso)

album_view.html (df_album_view.jpg)
artist_view.html (df_todo_artista.jpg)
genero_view.html (df_resultados_pinchar_en_un_genero.jpg)
## 3. NAVEGACIÓN (Rafa todo)

header.html
footer.html
sidebar_left.php
sidebar_right.php
## 4. REPRODUCCIÓN (Alberto y Denys)

play_music.html (sólo 1er plano de momento)
play_video.html
play_live.html
## 5. USUARIO REGISTRADO (Denis Pinto)

usr_registrado_main.html
usr_modificar_info.html 
usr_baja.html
## 6. ARTISTA

artista_main.html (Javier)
art_modificar_info.html (Javier)
art_baja.html (Javier)
upload_main.html (Javier)
    upload_song.html (Alberto)
    upload_video.html (Alberto)
    empezar_ensayo.html (Alberto)
    empezar_concierto.html (Alberto)
## 7. ADMINISTRADOR (Nacho)

admin_main.html
lista_usuarios.html (df_all_users_list.jpg)

**Comment by amiedes** [comment]
Trabajo Repartido.
- Nacho va a crear todos los archivos .html en el master, para que podamos hacer ya cada uno su branch y empezar a trabajar.
- MUY IMPORTANTE: no hagáis nunca un push al master directamente. Para trabajar creais una rama, creais un issue para esa rama y especificáis que archivos vais a modificar (Y NO TOQUÉIS NINGUNO MÁS).  No hagáis un push al master aunque sea para cambiar una falta ortográfica.
- Comentar si os parece bien cómo hemos repartido el trabajo.

**Comment by javber** [comment]
Me parece bien.
¿Podeis subir alguno algún ejemplo usando ese css que ha echo Rafa?No lo entiendo muy bien como utilizarlo.
Gracias.

**Comment by dpriver** [comment]
Puedes abrir este issue en el proyecto "Veery"?

**Comment by dpriver** [comment]
Genial, gracias.
