### ISSUE TITLE
Rama 'dev'

### ISSUE THREAD

**Issue by amiedes** [UCM-SistemasWeb-Veery/UCM-SistemasWeb-Veery.github.io#2]
De acuerdo con lo que comentaron en la charla sobre git el viernes pasado he decidido crear la rama 'dev' a partir del master. Mencionaron que lo normal es realizar todo el desarrollo sobre esta de tal forma que la versión presente en el master sea siempre funcional.

**Comment by densypko** [comment]
Pero antes de crear esta rama tenías que haber creado las carpetas en el master no?

**Comment by amiedes** [comment]
Acabo de crearlas en esta rama.

**Comment by amiedes** [comment]
He creado la estructura de carpetas y los archivos .html que habíamos acordado. Para empezar a trabajar podéis partir de esta rama.
A partir de ahora es importante que no hagáis ningún push ni a master ni a dev sin que lo hallamos acordado entre todos. En vuestras propias ramas podéis hacer lo que queráis.
