### ISSUE TITLE
Rama 'dev-uploads-alberto'

### ISSUE THREAD

**Issue by amiedes** [UCM-SistemasWeb-Veery/UCM-SistemasWeb-Veery.github.io#3]
He creado esta rama para trabajar sobre los siguientes archivos:

upload_song.html
upload_video.html
empezar_ensayo.html
empezar_concierto.html

Nota para Javier: no se si habrás visto que estamos trabajando ambos sobre el apartado 6. No obstante, esto no debería ser problema siempre y cuando yo mantenga los nombres de archivo que aparecen en el issue de los .html

**Comment by javber** [comment]
Si, sin problema.
